# Set the base image
FROM        redis:5.0.3-alpine

# File Author / Maintainer
#MAINTAINER InfiniteRain

# Update the repository and install Redis Server
#RUN         apt-get update && apt-get install -y redis-server

# Expose Redis port 6379
#EXPOSE      6379

# Run Redis Server
#ENTRYPOINT  ["/usr/bin/redis-server"]